### ISSUE TITLE
[Youtiba]: Roadmap (short-term)

### ISSUE THREAD

**Issue by YouDirk** [Shortsub/report#4]
### Label

enhancement (feature request)

### Operating system

unspecified (all, cross-platform)

### Detailed description

Currently short-termed road-map before implementing `class Renderer`:

* [x] Working build-system, called *Youtiba SDK* which will be delivered to licensed designers
* [x] Command-line `Subcommand/Subargument` parser
* [ ] OS-dependent `class ConfigIniFile` for configurations, like
  ```ini
  ; This is an ini-file.  Comments are starting with a ';' character.
  [General]
  Fullscreen=yes
  RenderResolution=1920x1080
  ...
  ```
* [ ] *Vulkan API* initialization
* [ ] OS-dependent `class RenderContext` initialization, like `WindowContext`, `ScreenContext`
* [ ] `class Timer` used by `Engine` tick
* [ ] Implementing a working `Engine::main_loop()`
* [x] Add documentation to *Youtiba SDK*, related to #2 
* [ ] Porting current development state of *Youtiba SDK* to *Windows*, related to #3
